<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/AvionParTerre.Core/AvionParTerre.Core.csproj" />
    <None Include="../../data/catalogue.json" Link="data/catalogue.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
